### PR TITLE
Pyfactor

### LINKED ISSUE #16: Whitespace causing expressions to no longer be correct-by-construction
Valid forms of `not` expressions in Python:

`not(True)`
`not True`
`not""`
`not{}`
`not 1`

Invalid Python:

`notTrue`
`not1`

Here's a simplified form of the AST:

```
data NotExpr
  = NotExprOne KNot [Whitespace] NotExpr
  | NotExprNone Comparison

data Symbol = SGt | SLt | ...

data Comparison
  = Gt Expr [Whitespace] SGt [Whitespace] Expr
  | Lt Expr [Whitespace] SLt [Whitespace] Expr
  | ...

data Expr = Number Int | True | False | None | String [Char] | Parens Expr | ...
```

This permits all the valid uses of `not`, but also some invalid uses. For example, one
could write `NotExprOne KNot [] (NotExprOne KNot [] ...`, which would result in
`notnot...`.

The true whitespace rule for `not` is this:

```
Given (NotExprOne a b c): If print(c) begins with an identifier character, then 'b' should not be empty.
```

If we were to encode this with types, it might look like this:

```
data NotExpr'
  = NotExprNone' Comparison'

data NotExpr
  = NotExprOne KNot (NonEmpty Whitespace) NotExpr
  | NotExprOne' KNot [Whitespace] Comparison'
  | NotExprNone Comparison

-- | Comparison' will not begin with an identifier character when printed
data Comparison'
  = Gt' Expr' [Whitespace] SGt [Whitespace] Expr
  | Lt' Expr' [Whitespace] SLt [Whitespace] Expr

-- | Expr' will not begin with an identifier character when printed
data Expr' = Parens' (Either Expr Expr') | String' [Char]

-- | Comparison will begin with an identifier character when printed
data Comparison
  = Gt Expr [Whitespace] SGt [Whitespace] Expr
  | Lt Expr [Whitespace] SLt [Whitespace] Expr

-- | Expr will begin with an identifier character when printed
data Expr = Number Int | True | False | None
```

We split terminals into two types- one that will begin with identifier characters when printed, and one that won't. Then we have to propagate this change to all the non-terminals. It essentially doubles the number of types and data constructors. A lot of this grammar https://docs.python.org/3.5/reference/grammar.html has to be duplicated to encode this. I'm skeptical of this approach due to the amount of code it requires.

---

Ideally I still want to have simple prisms on all these types to provide a good user interface.
Now it would have to look something like this:

```
class FromNot s ws | s -> ws where
  _Not :: Prism' NotExpr (KNot, ws, s)

instance FromNot NotExpr (NonEmpty Whitespace) where
  _Not = -- match on NotExprOne

instance FromNot Comparison' [Whitespace] where
  _Not = -- match on NotExprOne'

class FromComparison comp expr | comp -> expr where
  _Gt :: Prism' comp (expr, [Whitespace], SGt, [Whitespace], Expr)
  _Lt :: Prism' comp (expr, [Whitespace], SLt, [Whitespace], Expr)

instance FromComparison Comparison' Expr' where
  _Gt = -- match on Gt'
  _Lt = -- match on Lt'

instance FromComparison Comparison Expr where
  _Gt = -- match on Gt
  _Lt = -- match on Lt

instance FromComparison NotExpr Expr where
  _Gt = -- match on NotExprNone then Gt
  _Lt = -- match on NotExprNone then Lt

instance FromComparison NotExpr' Expr' where
  _Gt = -- match on NotExprNone' then Gt'
  _Lt = -- match on NotExprNone' then Lt'
```

### LINKED ISSUE #17: Smart constructors preclude useful optics
There are a bunch of syntax elements that are created using runtime validation, because a type-based correct-by-construction representation is too complex to be useful. All of these runtime-validated types are created using the smart constructor pattern. The problem is that smart constructors prevent helpful prisms.

Here's an example:

```
module NoNumbers (NoNumbers, mkNoNumbers, _NoNumbers) where

newtype NoNumbers = NoNumbers { unNoNumbers :: String }

mkNoNumbers :: String -> Maybe NoNumbers
mkNoNumbers s
  | any isDigit s = Nothing
  | otherwise = Just $ NoNumbers s

_NoNumbers :: Prism' NoNumbers String
_NoNumbers = prism NoNumbers (Just . unNoNumbers)
```

`_NoNumbers` is obviously wrong. `review _NoNumbers ~ NoNumbers`, which we were trying to hide in the first place.

How do we fix this?

1. `_NoNumbers :: Prism' (Maybe NoNumbers) String

   Now, `review _NoNumbers :: String -> Maybe NoNumbers`, which is `mkNoNumbers`. The downside is
   that `preview _NoNumbers :: Maybe NoNumbers -> Maybe String`, which will be a pain when chaining
   prisms.

2. `_NoNumbers :: Prism NoNumbers (Maybe NoNumbers) String String`

  Now `review _NoNumbers :: String -> Maybe NoNumbers` and `preview _NoNumbers :: NoNumbers -> Maybe String`. We can always get a string out, so let's downgrade to `Iso`

3. `_NoNumbers :: Iso NoNumbers (Maybe NoNumbers) String String`

  `view _NoNumbers :: NoNumbers -> String`
  `view (from _NoNumbers) :: String -> Maybe NoNumbers`

Now that we have an accurate optic, let's see how it fares in nested updates

```
{-# language TemplateHaskell #-}
module Test where

import Control.Lens
import NoNumbers       

testMkThing = Thing "hello" <$> ("goodbye" ^. getting (from _NoNumbers)) 
testSet =                                                                                                                                          
  let                                                                                                                                             
    a = testMkThing1 ^?! _Just                                                                       
  in                                                                                                                                                       
    a & traverseOf thingNoNumbers (_NoNumbers .~ "goodbye1") 
```

It turns out that in this context, an `Iso` is a burden. We could have achieve the same outcome with less code by using `mkNoNumbers` and `unNoNumbers` on their own:

```
testMkThing = Thing "hello" <$> mkNoNumbers "goodbye"
testSet =                                                                                                                                          
  let                                                                                                                                             
    a = testMkThing1 ^?! _Just                                                                       
  in                                                                                                                                                       
    a & traverseOf thingNoNumbers (\_ -> mkNoNumbers "goodbye1") 
```

### LINKED ISSUE #18: Is "syntactically correct by construction" worth it?
Until now, the approach to the AST has been "as correct-by-construction as possible, falling back to smart constructors when necessary". Since we've been getting closer to a complete representation, I have been considering another approach that gets similar levels of safety but permits a more elegant library design, and potentially better user experience.

Here it is, applied to a very small AST:

```
{-# language DataKinds, PolyKinds, LambdaCase, ViewPatterns #-}
module AST (AST, Val(..), _Int, _Add, _Assign, unvalidate, validate) where

import Control.Lens
import Data.Coerce

data Val = UV | V

data AST (a :: Val)
  = Int Int
  | Add (AST a) (AST a)
  | Assign String (AST a)
  deriving (Eq, Show)

_Int :: Prism (AST a) (AST UV) Int Int
_Int =
  prism
    Int
    (\case; (unvalidate -> Int a) -> Right a; (unvalidate -> a) -> Left a)

_Add :: Prism (AST a) (AST UV) (AST UV, AST UV) (AST UV, AST UV)
_Add =
  prism
    (uncurry Add)
    (\case; (unvalidate -> Add a b) -> Right (a, b); (unvalidate -> a) -> Left a)

_Assign :: Prism (AST a) (AST UV) (String, AST UV) (String, AST UV)
_Assign =
  prism
    (uncurry Assign)
    (\case; (unvalidate -> Assign a b) -> Right (a, b); (unvalidate -> a) -> Left a)

unvalidate :: AST a -> AST UV
unvalidate = coerce

validate :: AST UV -> Maybe (AST V)
validate (Int a) = Just $ coerce $ Int a
validate (Add a b) =
  fmap coerce $
  Add <$> (coerce <$> validate a) <*> (coerce <$> validate b)
validate (Assign a b)
  | a == "bad" = Nothing
  | otherwise =
    fmap coerce $
    Assign a <$> (coerce <$> validate b)
```

In this approach, I use a phantom type to indicate that the AST has been validated. Due to the types of the prisms, only unvalidated terms can be constructed, but terms of any validation status can be matched on. This means we can use the same data structure to represent validated and unvalidated terms. The current codebase has two distinct datatypes (with a lot of duplication). The other consequence is that *all* syntax-correction checking is moved to run-time. I don't believe this is a bad thing, considering the amount of checks that are already performed at run-time.

This pattern also fixes the optics problem that is demonstrated in #17. 

There is a small "safety" flaw with this approach, that a user can just use `coerce` to skip the validation stage. Currently I think that's an okay trade-off.

### PR DESCRIPTION
**Pull request by LightAndLight**
I have been working on a new formulation of `hpython` under the name of `pyfactor`. Its history can be found here https://github.com/lightandlight/pyfactor.

It's time for `pyfactor` to be merged. It is both simpler and more powerful than the previous incarnation and I'm confident it will be the way forward for this project.

Fixes #16 
Fixes #17 
Fixes #18

### CODE REVIEW

File: example/Example.hs [hunk 1]
```diff
@@ -0,0 +1,240 @@
...
+    []
+    ( CommaSepMany (PositionalParam a "element") [] [] $
+      CommaSepOne (KeywordParam a "to" [] [] (List a [] CommaSepNone []))
+    )
+    []
+    []
+    LF
+    (Block
+     [ ( a
+       , replicate 4 Space
```
Comment (tonymorris) [inline example/Example.hs]: Might be worth writing:

    space4 = replicate 4 Space

File: hpython.cabal [hunk 2]
```diff
@@ -2,167 +2,70 @@
...
 name:                hpython
-version:             0.0.1.0
-synopsis:            Write Python using Haskell
+version:             0.1.0.0
+-- synopsis:            
 -- description:         
-homepage:            https://github.com/qfpl/hpython
 license:             BSD3
-license-file:        LICENCE
+license-file:        LICENSE
```
Comment (tonymorris) [inline hpython.cabal]: LICENCE

File: hpython.cabal [hunk 3]
```diff
@@ -2,167 +2,70 @@
...
 author:              Isaac Elliott
 maintainer:          isaace71295@gmail.com
```
Comment (tonymorris) [inline hpython.cabal]: You'll get spam if this email address goes to hackage.

Recommend upside-down, or a mail alias.

File: src/Data/Validate.hs [hunk 4]
```diff
@@ -0,0 +1,22 @@
+{-# language DeriveFunctor, DeriveFoldable, DeriveTraversable #-}
+{-# language TemplateHaskell #-}
+module Data.Validate where
+
+import Control.Lens.TH
+import Data.Semigroup
+
+data Validate e a
```
Comment (tonymorris) [inline src/Data/Validate.hs]: ?

https://hackage.haskell.org/package/validation

File: src/Language/Python/Internal/Optics.hs [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+  } deriving (Eq, Show)
+makeLenses ''KeywordParam
+
+_KeywordParam
+  :: Prism
+       (Param v a)
+       (Param '[] a)
+       (KeywordParam v a)
+       (KeywordParam '[] a)
+_KeywordParam =
```
Comment (tonymorris) [inline src/Language/Python/Internal/Optics.hs]: I suspect this signature could be more polymorphic.

File: src/Language/Python/Internal/Parse.hs [hunk 6]
```diff
@@ -0,0 +1,249 @@
...
+    someCommaSep = do
+      val <- e
+      res <-
+        optional $
+          CommaSepMany val <$>
+          many whitespace <* char ',' <*>
+          many whitespace <*> commaSep e
+      case res of
+        Nothing -> pure $ CommaSepOne val
+        Just a -> pure a
```
Comment (tonymorris) [inline src/Language/Python/Internal/Parse.hs]: pure (fromMaybe (CommaSepOne val) res)

File: src/Language/Python/Internal/Parse.hs [hunk 7]
```diff
@@ -0,0 +1,249 @@
...
+      a <- atomExpr
+      v <-
+        optional
+          (try ((,,,) <$> many whitespace <*> spanned (string "**")) <*>
+           many whitespace <*>
+           factor)
+      case v of
+        Nothing -> pure a
+        Just (ws1, _ :~ s, ws2, b) ->
+          pure $ BinOp (a ^. exprAnnotation <> b ^. exprAnnotation) a ws1 (Exp s) ws2 b
```
Comment (tonymorris) [inline src/Language/Python/Internal/Parse.hs]: `pure` on both branches of the case/of

File: src/Language/Python/Internal/Parse.hs [hunk 8]
```diff
@@ -0,0 +1,249 @@
...
+
+level :: (CharParsing m, MonadState [[Whitespace]] m) => m ()
+level = (get >>= foldl (\b a -> b <* traverse parseWs a) (pure ())) <?> "level indentation"
+  where
+    parseWs Space = char ' '$> ()
+    parseWs Tab = char '\t' $> ()
+    parseWs (Continued nl ws) = pure ()
+
+dedent :: MonadState [[Whitespace]] m => m ()
+dedent = modify tail
```
Comment (tonymorris) [inline src/Language/Python/Internal/Parse.hs]: `tail` is suspicious
